version: "3.9"
  
services: 

  postgresql:
    image: "postgres:14-alpine"
    container_name: postgres
    volumes:
      - /etc/envs/.env:/etc/envs/.env
      - /etc/ai4birds-data-db/data:/var/lib/postgresql/data
      - ./data/postgresDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bird-net

  postgresql-ingest:
    image: "postgres:14-alpine"
    container_name: postgres-ingest
    volumes:
      - /etc/envs/.env:/etc/envs/.env
      - /etc/ai4birds-ingest-db/data:/var/lib/postgresql/data
      - ./data/postgresIngestDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_INGEST_USER}
      - POSTGRES_DB=${POSTGRES_INGEST_DB}
      - POSTGRES_PASSWORD=${POSTGRES_INGEST_PASSWORD}
    networks:
      - bird-net

  postgresql-analysis:
    image: "postgres:14-alpine"
    container_name: postgres-analysis
    volumes:
      - /etc/envs/.env:/etc/envs/.env
      - /etc/ai4birds-analysis-db/data:/var/lib/postgresql/data
      #- ./data/postgresAnalysisDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_ANALYSIS_USER}
      - POSTGRES_DB=${POSTGRES_ANALYSIS_DB}
      - POSTGRES_PASSWORD=${POSTGRES_ANALYSIS_PASSWORD}
    networks:
      - bird-net

  frontend:
    build: ./ia4birds-all/ai4birds-web/ai4birds-web-app-frontend
    container_name: frontend
    ports:
      - 80:5173
      - 8080:8080
      - 443:443
    networks:
      - bird-net

  backend:
    build: ./ia4birds-all/ai4birds-web/ai4birds-web-app-backend
    container_name: backend
    volumes:
      - /etc/letsencrypt/archive/ia4birds-platform.air-institute.com:/etc/letsencrypt/archive/ia4birds-platform.air-institute.com
    ports:
      - 5030:3030
    networks:
      - bird-net

  ai4birds-ai-service:
      build: ./ia4birds-all/ai4birds-ai-service
      container_name: ai4birds-ai
      ports:
        - 5000:5000
      networks:
        - bird-net 

  ai4birds-coordinate-service:
      build: ./ia4birds-all/ai4birds-coordinate-service
      container_name: ai4birds-coordinate
      ports:
        - 5001:5000
      networks:
        - bird-net 
     
  ai4birds-ingest-service:
      build: ./ia4birds-all/ai4birds-ingest-service
      container_name: ai4birds-ingest
      mem_limit: 6g
      volumes:
        - /home/bisite/exclusion_eolica.csv:/home/exclusion_eolica.csv
      ports:
        - 5002:5000
      env_file: 
        - .env
      networks:
        - bird-net 

  redis:
    image: redis:6.2-alpine
    container_name: redis
    env_file:
      - /etc/envs/.env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data
      - /etc/envs/.env:/etc/envs/.env
    networks:
      - bird-net
      - redis-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    env_file:
      - /etc/envs/.env
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - 8081:8081
    volumes:
      - /etc/envs/.env:/etc/envs/.env
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  bird-net:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  cache:
    driver: local

