version: "3.9"
  
services: 

  # postgresql:
  #   image: "postgres:11-alpine"
  #   container_name: postgresql
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - /etc/ai4birds-ddbb-raw/data:/var/lib/postgresql/data
  #     - ./kong.sql:/docker-entrypoint-initdb.d/kong.sql
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=kong
  #     - POSTGRES_PASSWORD=postgres
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 30s
  #     timeout: 3s
  #     retries: 5
  #   networks:
  #     - bird-net 

  # kong-prepare:
  #   image: kong:2.8.1-alpine
  #   # command: "kong migrations bootstrap"
  #   restart: on-failure
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: postgresql
  #     KONG_PG_DATABASE: kong
  #     KONG_PG_USER: postgres
  #     KONG_PG_PASSWORD: postgres
  #   links:
  #     - postgresql
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - bird-net 

  # kong:
  #   image: my-custom-kong:latest
  #   # command: "kong migrations up"
  #   healthcheck:
  #     test: ["CMD", "kong", "health"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #   restart: on-failure:5
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: postgresql
  #     KONG_PG_USER: postgres
  #     KONG_PG_PASSWORD: postgres
  #     KONG_DB_UPDATE_FREQUENCY: 1m
  #     KONG_ADMIN_GUI_URL : "http://localhost:8002"
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_PROXY_LISTEN: '0.0.0.0:8000, 0.0.0.0:8443 ssl'
  #     KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
  #     KONG_PLUGINS: bundled,kong-spec-expose
  #   depends_on:
  #     - kong-prepare
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"
  #     - "8002:8002"
  #     - "8444:8444"
  #     - "8443:8443"
  #   networks:
  #     - bird-net 

  # konga:
  #   image: pantsel/konga:0.14.9
  #   restart: unless-stopped
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - "1337:1337"
  #   networks:
  #     - bird-net
      
  # app:
  #   build: ./ia4birds-all/ai4birds-web
  #   container_name: app
  #   ports:
  #     - 8080:8080
  #     - 80:80
  #     - 5173:5173
  #     - 443:443
  #     - 3000:3030
  #   networks:
  #     - bird-net

  postgresql:
    image: "postgres:14-alpine"
    container_name: postgres
    volumes:
      - /etc/envs/.env:/etc/envs/.env
      - /etc/ai4birds-data-db/data:/var/lib/postgresql/data
      - ./data/postgresDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bird-net

  postgresql-ingest:
    image: "postgres:14-alpine"
    container_name: postgres-ingest
    volumes:
      - /etc/envs/.env:/etc/envs/.env
      - /etc/ai4birds-ingest-db/data:/var/lib/postgresql/data
      - ./data/postgresIngestDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_INGEST_USER}
      - POSTGRES_DB=${POSTGRES_INGEST_DB}
      - POSTGRES_PASSWORD=${POSTGRES_INGEST_PASSWORD}
    networks:
      - bird-net

  postgresql-analysis:
    image: "postgres:14-alpine"
    container_name: postgres-analysis
    volumes:
      - /etc/envs/.env:/etc/envs/.env
      - /etc/ai4birds-analysis-db/data:/var/lib/postgresql/data
      #- ./data/postgresAnalysisDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_ANALYSIS_USER}
      - POSTGRES_DB=${POSTGRES_ANALYSIS_DB}
      - POSTGRES_PASSWORD=${POSTGRES_ANALYSIS_PASSWORD}
    networks:
      - bird-net

  frontend:
    build: ./ia4birds-all/ai4birds-web/ai4birds-web-app-frontend
    container_name: frontend
    ports:
      - 80:5173
      - 8080:8080
      - 443:443
    networks:
      - bird-net

  backend:
    build: ./ia4birds-all/ai4birds-web/ai4birds-web-app-backend
    container_name: backend
    ports:
      - 5030:3030
    networks:
      - bird-net


  ai4birds-ai-service:
      build: ./ia4birds-all/ai4birds-ai-service
      container_name: ai4birds-ai
      ports:
        - 5000:5000
      networks:
        - bird-net 

  ai4birds-coordinate-service:
      build: ./ia4birds-all/ai4birds-coordinate-service
      container_name: ai4birds-coordinate
      ports:
        - 5001:5000
      networks:
        - bird-net 
     
  ai4birds-ingest-service:
      build: ./ia4birds-all/ai4birds-ingest-service
      container_name: ai4birds-ingest
      mem_limit: 6g
      volumes:
        - /home/bisite/exclusion_eolica.csv:/home/exclusion_eolica.csv
      ports:
        - 5002:5000
      env_file: 
        - .env
      networks:
        - bird-net 

  redis:
    image: redis:6.2-alpine
    container_name: redis
    env_file:
      - /etc/envs/.env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data
      - /etc/envs/.env:/etc/envs/.env
    networks:
      - bird-net
      - redis-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    env_file:
      - /etc/envs/.env
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - 8081:8081
    volumes:
      - /etc/envs/.env:/etc/envs/.env
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  bird-net:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  cache:
    driver: local

