services:

  postgresql:
    image: "postgres:14-alpine"
    container_name: postgres
    env_file:
      - /etc/envs/.env
    volumes:
      - ./data/postgresDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - bird-net

  postgresql-ingest:
    image: "postgres:14-alpine"
    container_name: postgres-ingest
    env_file:
      - /etc/envs/.env
    volumes:
      - /etc/ai4birds-ingest-db/data:/var/lib/postgresql/data
      - ./data/postgresIngestDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_INGEST_USER}
      - POSTGRES_DB=${POSTGRES_INGEST_DB}
      - POSTGRES_PASSWORD=${POSTGRES_INGEST_PASSWORD}
    networks:
      - bird-net

  postgresql-analysis:
    image: "postgres:14-alpine"
    container_name: postgres-analysis
    env_file:
      - /etc/envs/.env
    volumes:
      - /etc/ai4birds-analysis-db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_ANALYSIS_USER}
      - POSTGRES_DB=${POSTGRES_ANALYSIS_DB}
      - POSTGRES_PASSWORD=${POSTGRES_ANALYSIS_PASSWORD}
    networks:
      - bird-net

  frontend:
    build: ./ia4birds-all/ai4birds-web/ai4birds-web-app-frontend
    container_name: frontend
    ports:
      # - 80:5173
      - 8080:8080
      # - 443:443
    env_file:
      - /etc/envs/.env
    networks:
      - bird-net

  backend:
    build: ./ia4birds-all/ai4birds-web/ai4birds-web-app-backend
    container_name: backend
    env_file:
      - /etc/envs/.env
    volumes:
      - /etc/letsencrypt/archive/ia4birds-platform.air-institute.com:/etc/letsencrypt/archive/ia4birds-platform.air-institute.com
      - ./hls-stream:/home/node/app/hls-stream
    ports:
      - 5030:3030
    depends_on:
      - postgresql
      - redis
    networks:
      - bird-net

  webserver:
    depends_on:
      - frontend
      - backend
    build:
      context: .
      dockerfile: nginx_dockerfile/Dockerfile
      args:
        ENVIRONMENT: "${ENVIRONMENT}"
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - bird-net

  ai4birds-ai-service:
    build: ./ia4birds-all/ai4birds-ai-service
    container_name: ai4birds-ai
    ports:
      - 5000:5000
    networks:
      - bird-net

  ai4birds-coordinate-service:
    build: ./ia4birds-all/ai4birds-coordinate-service
    container_name: ai4birds-coordinate
    env_file:
      - /etc/envs/.env
    ports:
      - 5001:5000
    networks:
      - bird-net

  ai4birds-ingest-service:
      build: ./ia4birds-all/ai4birds-ingest-service
      container_name: ai4birds-ingest
      mem_limit: 6g
      memswap_limit: 6g
      env_file: 
        - /etc/envs/.env
      volumes:
        - /home/bisite/exclusion_eolica.csv:/home/exclusion_eolica.csv
        - ./ia4birds-all/ai4birds-ingest-service/ai4birds_ingest_service/heatmaps:/app/ai4birds_ingest_service/heatmaps
      ports:
        - 5002:5000
      networks:
        - bird-net 

  redis:
    image: redis:6.2-alpine
    container_name: redis
    env_file:
      - /etc/envs/.env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes:
      - cache:/data
    networks:
      - bird-net
      - redis-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    env_file:
      - /etc/envs/.env
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_COMMANDER_USER}
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - redis-net

  mediamtx:
    build: ./mediamtx-custom
    container_name: mediamtx
    ports:
      - "8554:8554"        # RTSP
      - "9997:9997"        # RTMP / API
      - "8889:8889"        # RTMP (in)
      - "8890:8890/udp"    # UDP (SRT / RTP)
      - "8189:8189"        # Control API (REST)
    expose:
      - "8888"             # HLS (solo accesible desde NGINX)
    volumes:
      - camara-config:/app/config
    networks:
      - bird-net


  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ${MQTT_CONFIG_VOLUME}
      - ${MQTT_DATA_VOLUME}
      - ${MQTT_LOG_VOLUME}
    env_file:
      - /etc/envs/.env
    ports:
      - "5083:1883"
      - "9001:9001"
    networks:
      - bird-net


  celery-worker:
    build: ./ia4birds-all/ai4birds-ingest-service
    container_name: celery-worker
    command: celery -A ai4birds_celery.app worker --loglevel=info
    env_file:
      - /etc/envs/.env
    depends_on:
      - ai4birds-ingest-service
      - redis
    networks:
      - redis-net
      - bird-net

  celery-beat:
    build: ./ia4birds-all/ai4birds-ingest-service
    container_name: celery-beat
    command: celery -A ai4birds_celery.app beat --loglevel=info
    env_file:
      - /etc/envs/.env
    depends_on:
      - ai4birds-ingest-service
      - celery-worker
    networks:
      - redis-net
      - bird-net

networks:
  bird-net:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  ia4birds_videos_data:
    external: true
  cache:
    driver: local
  camara-config:

