## App reverse proxy

# Mapea upgrade para websockets
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# HTTP to HTTPS redirection
server {
    listen 80;
    listen [::]:80;

    server_name ia4birds-platform.air-institute.com www.ia4birds-platform.air-institute.com;

    return 301 https://$host$request_uri;
}

# HTTPS config
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ia4birds-platform.air-institute.com www.ia4birds-platform.air-institute.com;

    ssl_certificate /etc/letsencrypt/live/ia4birds-platform.air-institute.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ia4birds-platform.air-institute.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;

    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # WebSocket para Vite/dev o features en el front
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;

        proxy_read_timeout 300s;
    }

    location /api/ {
        proxy_pass http://backend:3030;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;

        proxy_connect_timeout 60s;
        proxy_send_timeout    300s;
        proxy_read_timeout    300s;
    }
}

## MQTT reverse proxy
# HTTP redirection
server {
    listen 80;
    listen [::]:80;
    server_name mqtt.ia4birds-platform.air-institute.com;
    return 301 https://$host$request_uri;
}

# HTTPS config
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name mqtt.ia4birds-platform.air-institute.com;

    ssl_certificate     /etc/letsencrypt/live/mqtt.ia4birds-platform.air-institute.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mqtt.ia4birds-platform.air-institute.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://mosquitto:9001;
        proxy_http_version 1.1;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
    }
}