## App reverse proxy
# HTTP to HTTPS redirection
server {
    listen 80;
    listen [::]:80;

    server_name ia4birds-platform.air-institute.com www.ia4birds-platform.air-institute.com;

    return 301 https://$host$request_uri;
}

# HTTPS config
server {
    listen 443;
    listen [::]:443;

    server_name ia4birds-platform.air-institute.com www.ia4birds-platform.air-institute.com;

    ssl_certificate /etc/letsencrypt/live/ia4birds-platform.air-institute.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ia4birds-platform.air-institute.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://frontend:5173
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}