name: Build Ai Service

on:
  push:
    branches:
      - 'pre'
    paths:
      - 'ia4birds-all/ai4birds-ai-service/**'

jobs:
  check-out:
    name: check out
    runs-on: [self-hosted, linux, x64, pre]
    steps:
      - uses: actions/checkout@v1

  docker-clean:
    name: docker clean
    needs: check-out
    runs-on: [self-hosted, linux, x64, pre]
    steps:
      - name: Stop ai4birds-ai Container
        run: sudo docker stop ai4birds-ai
        continue-on-error: true
      - name: Remove ai4birds-ai Container
        run: sudo docker rm ai4birds-ai
        continue-on-error: true
      - name: Remove ia4birds-all-ia4birds-ai-service Image
        run: sudo docker rmi ia4birds-all-ia4birds-ai-service
        continue-on-error: true

  docker-compose:
    name: docker compose
    needs: docker-clean
    runs-on: [self-hosted, linux, x64, pre]
    steps:
      - name: Build the docker-compose
        run: sudo docker compose -f "docker-compose.yml" up -d --build ai4birds-ai-service