name: Docker Debug

on:
  push:
    branches:
      - 'pre'

jobs:
  check_out:
    runs-on: [self-hosted, linux, x64, pre]
    steps:
      - name: Stop old containers
        run: docker stop $(docker ps -a -q) || true
      - name: Remove old containers
        run: docker rm $(docker ps -a -q) || true
      - name: Remove old images
        run: docker rmi $(docker images -a -q) || true
      - name: Clear all Docker
        run: docker system prune --all -f || true

        run: echo "Runner is working!"

# name: Build all

# on:
#   push:
#     branches:
#       - 'pre'

# jobs:
#   check_out:
#     name: check out
#     runs-on: [self-hosted, linux, x64, pre]  
#     steps:
#      - uses: actions/checkout@v1
#      - name: stop old container
#        run: sudo docker stop $(docker ps -a -q)
#        continue-on-error: true
#      - name: remove old container
#        run: sudo docker rm $(docker ps -a -q)
#        continue-on-error: true
#      - name: remove old image
#        run: sudo docker rmi $(docker images -a -q)
#        continue-on-error: true
#      - name: clear all docker
#        run: sudo docker system prune --all -f

#   docker_compose:
#     name: docker compose
#     needs: check_out
#     runs-on: [self-hosted, linux, x64, pre]
#     steps:
#     - name: Build Custom Kong Image
#       run: sudo docker build -t my-custom-kong:latest .
#     - name: Build the docker-compose
#       run: sudo docker compose -f "docker-compose.yml" up -d

  # scan_with_trivy:
  #   name: scan with trivi
  #   needs: docker_compose
  #   runs-on: [self-hosted, linux, x64, pre]
  #   steps:
  #     - name: Run Trivy vulnerability scanner in fs mode
  #       uses: anandg112/trivy-action@feat/add-skip-dirs-option
  #       with:
  #         image-ref: $(docker images -a -q)
  #         scan-type: 'fs'
  #         scan-ref: '.'
  #         ignore-unfixed: true
  #         format: 'table'
  #       #  output: 'trivy-results-fs.sarif'
  #       #  severity: 'CRITICAL,HIGH'
  #         skip-dirs: "ignored-dir"
      
