name: Build pre

on:
  push:
    branches:
      - 'pre'

jobs:
  check_out:
    name: check out
    runs-on: [self-hosted, linux, x64, pre]
    steps:
      - uses: actions/checkout@v1
      # - name: Stop old containers
      #   run: sudo docker stop $(docker ps -a -q)
      #   continue-on-error: true
      # - name: Remove old containers
      #   run: sudo docker rm $(docker ps -a -q)
      #   continue-on-error: true
      - name: Stop old containers except rtsp-stream and nginx-hls
        run: sudo docker ps -a --format '{{.ID}} {{.Names}}' | awk '!/rtsp-stream|nginx-hls/ {print $1}' | xargs -r sudo docker stop
        continue-on-error: true
      - name: Remove old containers except rtsp-stream and nginx-hls
        run: sudo docker ps -a --format '{{.ID}} {{.Names}}' | awk '!/rtsp-stream|nginx-hls/ {print $1}' | xargs -r sudo docker rm
        continue-on-error: true

      - name: Remove old images
        run: sudo docker rmi $(docker images -a -q)
        continue-on-error: true
      - name: Clear all Docker
        run: sudo docker system prune --all -f || true

  docker_compose:
    name: docker compose
    needs: check_out
    runs-on: [self-hosted, linux, x64, pre]
    steps:
      - name: Build and run docker-compose
        run: docker compose -f docker-compose.yml --env-file /etc/envs/.env up -d --build --remove-orphans

      - name: List running containers
        run: docker ps
